### ISSUE TITLE
Uglify failed

### ISSUE THREAD

**Issue by owenyang0** [eCollect/vue-swipe-actions#1]
When I did uglify my component, I got `Unexpected token` error. This was caused by vue-cli, please simply update vue-cli and republish this package to npm again.

Thanks,
```
SyntaxError: Unexpected token: name (i) [./~/vue-swipe-actions/dist/vue-swipe-actions.common.js:705,0]
```

The issue file is here: `vue-swipe-actions/node_modules/@vue/cli-service/lib/commands/build/setPublicPath.js`
## Before
```js
if (typeof window !== 'undefined') {
  let i
  if ((i = window.document.currentScript) && (i = i.src.match(/(.+\/)[^/]+\.js$/))) {
    __webpack_public_path__ = i[1] // eslint-disable-line
  }
}
```
## Now
```js
if (typeof window !== 'undefined') {
  var i
  if ((i = window.document.currentScript) && (i = i.src.match(/(.+\/)[^/]+\.js$/))) {
    __webpack_public_path__ = i[1] // eslint-disable-line
  }
}
```

**Comment by FluksikartonGOD** [comment]
Solved with [this pull request](https://github.com/eCollect/vue-swipe-actions/pull/2).
