### ISSUE TITLE
Disable list scrolling while swiping left and right?

### ISSUE THREAD

**Issue by lilong7676** [eCollect/vue-swipe-actions#14]
is that possible?

**Comment by nanov** [comment]
It is actually disabled, or you mean body scrolling?

**Comment by lilong7676** [comment]
yes,while swiping left, make whole list pause scroling,just like the native iOS UITableviewCell

**Comment by lilong7676** [comment]
because The list is too sensitive while swipe left

**Comment by nanov** [comment]
Are you testing it on a phone or pc, do you have a test case, or could we use the demo with more items in it for example?

Preventing the whole body form scrolling is fairly trivial, you can add your own class on active event.
Preventing the list could be done in similar manner.

**Comment by nanov** [comment]
Ok I've got it tested on my iPhone and i see what you mean, will release a fix right away.

**Comment by nanov** [comment]
Just released [2.0.0-beta.4](https://github.com/eCollect/vue-swipe-actions/releases/tag/v2.0.0-beta.4) which should address this issue ( on phone devices, for desktop ones still class manipulation on the body/element is the preferred way ).

Please let me know if this works for you.

**Comment by lilong7676** [comment]
That's awesome,it's a elegant solution to my problem, Thanks!
