### ISSUE TITLE
SwipeOut -- bug on `revealLeft`

### ISSUE THREAD

**Issue by jacquescrocker** [eCollect/vue-swipe-actions#16]
https://github.com/eCollect/vue-swipe-actions/blob/master/src/components/SwipeOut.js#L43

i think it should be `!this.$refs.left` instead of `!this.$refs.right`

Net result: `revealLeft` does not function if there is no `right` slot

**Comment by nanov** [comment]
Good catch, will be fixed!

**Comment by nanov** [comment]
Fixed with last release.
