### ISSUE TITLE
Do you have any animation options?

### ISSUE THREAD

**Issue by Jae-kwang** [eCollect/vue-swipe-actions#20]
I am using your library with great appreciation.
but I needed some customize to use it.
I am using options such as 'animationDuration' and 'animationTimingFunction'.
Do you have plans to add options for animation?

**Comment by nanov** [comment]
Could you be more specific?

Animations timings are controlled [from css](https://github.com/eCollect/vue-swipe-actions/blob/71284f7dc5eff99c2cac19ebf42d5914b9986872/src/styles/vue-swipe-actions.css#L25).

**Comment by Jae-kwang** [comment]
Thank a lot. I was able to solve my problem with css. Thank you again for your help.
