### ISSUE TITLE
Ability to close all on SwipeOut component?

### ISSUE THREAD

**Issue by drewrawitz** [eCollect/vue-swipe-actions#21]
I see that there's a method for the `SwipeList` component (`closeActions`) but I can't seem to use that when using the `SwipeOut` component.

I need to programmatically close any open reveals. Is this currently possible?

Thanks!

**Comment by drewrawitz** [comment]
Got it to work via: `this.$refs.swipeItem.forEach(i => i.close());`

**Comment by nanov** [comment]
Hi,

you have two possibilities :

* using the ```close``` method
* for even more control, one may pass the ```revealed``` with the ```sync``` modifier and set it to null ( or empty string / undefined ).

**Comment by drewrawitz** [comment]
Thanks so much for the quick reply, @nanov! I went with option #1 :)

**Comment by CesarGomezTissini** [comment]
The problem is when I try to use it, console show me "TypeError: this.$refs.items.forEach is not a function".

**Comment by nanov** [comment]
@CesarGomezTissini Thank you for your comment, I'll take a look

**Comment by nanov** [comment]
@CesarGomezTissini : Fixed in beta.14!

Again thank you for your feedback.

**Comment by CesarGomezTissini** [comment]
Look like `swipeout:click` is broken too. You should check all events implemented due to recent changes you did in component.
