### ISSUE TITLE
Can I 'disabled' each item individually?

### ISSUE THREAD

**Issue by Jae-kwang** [eCollect/vue-swipe-actions#23]
I want features that each item is disabled individually.

Currently, if I pass 'disabled' props, all items will be disabled.

If you don't mind, can I send "PR" what I think?

**Comment by nanov** [comment]
Sure, PRs are welcome!

**Comment by nanov** [comment]
Again thank you for your PR (#25).
I did implement it in a somehow more generic way ( landed in beta.15 ), SwipeList has now a ```item-disabled``` property which accepts a function with the following signature ```(item) => condition```.

You can see it [here](https://github.com/eCollect/vue-swipe-actions/blob/c45fa0df9af79c8c79a7dcb783cc6ba11664b407/demo/src/App.vue#L10) in action.

**Comment by Jae-kwang** [comment]
Thank you. It was a must feature to me. :)
