### ISSUE TITLE
Prevent Event trigger on empty list

### ISSUE THREAD

**Issue by Jae-kwang** [eCollect/vue-swipe-actions#26]
A lot of your support is helping me much. Really thank you again. 🤩 
Can I ask you one more question?

I don't have a swap list on the left. 
So I don't render left swipe list. (Using v-if)

However, the 'leftRevealed' event is still being triggered. (Your demo too)
How can I prevent event triggers in that direction if I do not have a list? 🤔

**Comment by nanov** [comment]
Definitely a bug, fix just landed in beta.16.
