### ISSUE TITLE
Swipeout:click broken

### ISSUE THREAD

**Issue by CesarGomezTissini** [eCollect/vue-swipe-actions#27]
Look like @swipeout:click is broken too. Do nothing in fact. I was able to reproduce in our internal project. The code look like this:

```html
<swipe-list
     ref="list"
     class="card"
     :items="notifications"
     item-key="id"
     @swipeout:click="notify"
>
...
</swipe-list>
```

```javascript
notify: function(e) {
  this.bodyMessage = e.bodyMessage
  this.titleMessage = e.titleMessage
}
```

**Comment by nanov** [comment]
Also a bug. In fact regression. I’ll publish a fix tomorrow because I’m writing from my phone.

**Comment by nanov** [comment]
BTW: you can attach normal click events inside the scoped slots and achieve the same. In fact I think it‘s the better option.

**Comment by nanov** [comment]
```swipeout:click``` is back in beta.17, still the native click event is the preferred way of attaching events.
