### ISSUE TITLE
Not Trigger 'Closed Event'

### ISSUE THREAD

**Issue by Jae-kwang** [eCollect/vue-swipe-actions#28]
https://github.com/eCollect/vue-swipe-actions/issues/26 
You fixed that is. thank you. :)

But. If there is no list on the left side.
Swipe from left to right will not trigger the 'closed' event.
(like right swipe motion)

> Moving a short distance will trigger the 'closed' event

**Comment by nanov** [comment]
Thank you, Fixed in beta.17!
