### ISSUE TITLE
swipe-list does not refresh properly when items array changes

### ISSUE THREAD

**Issue by ruben82** [eCollect/vue-swipe-actions#3]
Hi,
thanks' for this plugin... I think is very useful.
I have a problem If I have to change a button visibility.
I must show a list of notifications, and the slide button have to help user to mark to read or delete a notification. The icon for "Marking to read" is visible if and only if flag called "FRead" is a "N" (I apply v-if ="item.FRead === ''N" on the icon div ).
If a notification is not read, i have two icons: one to set read a notification and another to delete it. If I set notification to "READ", item flag is changed to "Y". Button is hidden but the space remains.

Before:

<img width="199" alt="schermata 2018-10-03 alle 10 21 52" src="https://user-images.githubusercontent.com/3014501/46398733-2d5b1b00-c6f6-11e8-9604-02af058136d9.png">

After:

<img width="223" alt="schermata 2018-10-03 alle 10 14 27" src="https://user-images.githubusercontent.com/3014501/46398660-fbe24f80-c6f5-11e8-8576-b946503c7c16.png">

Compared with the first notification (the rightest one)

<img width="201" alt="schermata 2018-10-03 alle 10 24 35" src="https://user-images.githubusercontent.com/3014501/46398874-9773c000-c6f6-11e8-8261-90a0ef41e546.png">

How can I to refresh the width of buttons' content div, please?
Thanks' in advance for your reply

**Comment by nanov** [comment]
Hi.

This is a use case that didn't occurred to us. I think i know what may be causing the problem, let me inspect it.

I the meanwhile, if you could submit a test-case repository/gist it help a lot.

**Comment by nanov** [comment]
I have just released v1.0.6, size is calculated on each **slide start**, this means that as long as you do not change the size of the actions during the swipe process or while they are open, you should be fine.

Again, if you provide some kind of example repro I could come in greater help.

Regards.
