### ISSUE TITLE
Doesn't render items content

### ISSUE THREAD

**Issue by DmitryYuroskulov** [eCollect/vue-swipe-actions#34]
I do everything as in the example, the left and right slots render perfectly, but the contents of the element do not render.

![image](https://user-images.githubusercontent.com/43011788/62365970-5bdc9900-b547-11e9-84ae-86283c6e1621.png)

I expected the specified template with data

![image](https://user-images.githubusercontent.com/43011788/62366046-9f370780-b547-11e9-9864-2e3d5bfe0733.png)

![image](https://user-images.githubusercontent.com/43011788/62366134-e02f1c00-b547-11e9-9845-f9f3ffe04d51.png)

**Comment by nanov** [comment]
Could you share an example repro or a gist, is the example working for you?

I would try and use the [v-slot](https://vuedose.tips/tips/new-v-slot-directive-in-vue-js-2-6-0/) directive anyways.

**Comment by DmitryYuroskulov** [comment]
@nanov i just try to use.
now i try v-slot, and now the left and right slots do not render



[test.zip](https://github.com/eCollect/vue-swipe-actions/files/3461027/test.zip)

**Comment by nanov** [comment]
this file includes only your vue file, what about your application setup and build procedure? at least package.json.

**Comment by nanov** [comment]
What version of vue are you using?

**Comment by DmitryYuroskulov** [comment]
@nanov, i use nuxtjs.

[package.zip](https://github.com/eCollect/vue-swipe-actions/files/3461063/package.zip)

**Comment by nanov** [comment]
As far as i can see you are using an outdated version of nuxt, and possibly of vue as well.
Also the version of the demo you are using may be somehow outdated.
[Take a look at the current one](https://github.com/eCollect/vue-swipe-actions/blob/master/demo/src/App.vue).


I am sorry but I cannot really help you without some sort of working ( reproducible ) example.

**Comment by DmitryYuroskulov** [comment]
@nanov Now i install the latest version and its rendered, but styles broken, can u help?
[test repos](https://github.com/DmitryYuroskulov/nuxtTest)
![image](https://user-images.githubusercontent.com/43011788/62369236-cd6d1500-b550-11e9-819b-67b8de4ecc75.png)

**Comment by nanov** [comment]
Have you included the css provided with the library?

Something like this:
```js
import 'vue-swipe-actions/dist/vue-swipe-actions.css';
```

**Comment by DmitryYuroskulov** [comment]
@nanov now its works ;), thank you
