### ISSUE TITLE
How to use swipe-out component?

### ISSUE THREAD

**Issue by siberiadev** [eCollect/vue-swipe-actions#37]
Hey there! there is good doc for swipe-list component.
But is it possible to use swipe-out component out of list just for along item?

**Comment by nanov** [comment]
Hi There!

It if totally possible and fine to use **SwipeOut** component standalone.
Basically it accepts two scoped three scopes slots :
* **Left** with a ```close``` method inside scope for left hand side actions
* **Right** with a ```close``` method inside scope property for right hand actions
* **Default** with ```close```, ```revealRight```, ```revealLeft``` methods, and ```revealed``` boolean property inside scope for the actual content.

**Comment by siberiadev** [comment]
Thanx a lot man. I'll try it
